---
title: "R Programming: Zero to Pro"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

### Exercise 2

#### Part 1: Use R as a calculator

What is the square root of 289?
```{r square-root-of-289, exercise=TRUE}

```

```{r square-root-of-289-solution}
sqrt(289)
```


What is 18 to the power of 3?
```{r cubic, exercise=TRUE}

```

```{r cubic-solution}
18^3
```

 

```{r d-plus-e, echo=FALSE}
quiz(
  question("How many of the following expressions equal 3?",
    answer("0"),
    answer("1"),
    answer("2"),
    answer("3", correct = T)
  ),
    caption = NULL
)
```

```{r log, echo = TRUE, eval = FALSE}
log(exp(3))
log10(1000)
log(216, 6)
```


#### Part 2: Assignment

Create a  numeric variable called  "x" with value 2021, then display its value.
```{r 2021, exercise=TRUE}

```

```{r 2021-solution}
x <- 2021
x
```

Create a sequence called "y" containing the sequence of integers from 1 to 10, then display its value.
```{r seq_cre, exercise=TRUE}

```

```{r seq_cre-solution}
y <- 1:10
y
```

```{r numeric-plus-vector, echo=FALSE}
quiz(
  question("Will there an be error for 'x + y'?",
    answer("Yes"),
    answer("No", correct = T)
  ),
    caption = NULL
)
```


Creat a string called "z" with value "sheepstudio", then display its value.
```{r sheepstudio, exercise=TRUE}

```

```{r sheepstudio-solution}
z <- "sheepstudio"
z
```
